# Change this to # of pages of your Letterboxd Watchlist at letterboxd.com/[you]/watchlist
max_page: 28  
# Change this to your Letterboxd username
letterboxd_username: jornado  
# This is the file that will ultimately contain all the films sorted by service!
output_filename: "sorted_by_service.txt" 
# Change these to subscriptions you have (you can check providers.json)
my_services:
  - hbm: HBO Max
  - hlu: Hulu
  - dnp: Disney+
  - nfx: Netflix
  - amp: Amazon Prime Video
  - crc: Criterion Channel
